//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optepafi.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowLocal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optepafi.Assets.Localization.MainWindowLocal", typeof(MainWindowLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ElevConfig_CancelButton {
            get {
                return ResourceManager.GetString("ElevConfig_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ElevConfig_DownloadButton {
            get {
                return ResourceManager.GetString("ElevConfig_DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation data source.
        /// </summary>
        public static string ElevConfig_ElevSourceTextBlock {
            get {
                return ResourceManager.GetString("ElevConfig_ElevSourceTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ElevConfig_PasswordTextBlock_Watermark {
            get {
                return ResourceManager.GetString("ElevConfig_PasswordTextBlock_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of region:.
        /// </summary>
        public static string ElevConfig_RegionNameTextBlock {
            get {
                return ResourceManager.GetString("ElevConfig_RegionNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ElevConfig_RemoveButton {
            get {
                return ResourceManager.GetString("ElevConfig_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ElevConfig_ReturnButton {
            get {
                return ResourceManager.GetString("ElevConfig_ReturnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ElevConfig_UserNameTextBlock_Watermark {
            get {
                return ResourceManager.GetString("ElevConfig_UserNameTextBlock_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Menu_CreatePathFindingSessionButton {
            get {
                return ResourceManager.GetString("Menu_CreatePathFindingSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path finding.
        /// </summary>
        public static string Menu_PathFindingSessionTextBlock {
            get {
                return ResourceManager.GetString("Menu_PathFindingSessionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_SettingsButton {
            get {
                return ResourceManager.GetString("Menu_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations: .
        /// </summary>
        public static string Settings_ConfigurationsTextBlock {
            get {
                return ResourceManager.GetString("Settings_ConfigurationsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation data configuration.
        /// </summary>
        public static string Settings_ElevConfigEntryButton {
            get {
                return ResourceManager.GetString("Settings_ElevConfigEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string Settings_LocalizationTextBlock {
            get {
                return ResourceManager.GetString("Settings_LocalizationTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string Settings_MainMenuButton {
            get {
                return ResourceManager.GetString("Settings_MainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main settings.
        /// </summary>
        public static string Settings_MainSettingsHeader {
            get {
                return ResourceManager.GetString("Settings_MainSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication token.
        /// </summary>
        public static string ElevConfig_AuthenticationTokenTextBlock_Watermark{
            get {
                return ResourceManager.GetString("ElevConfig_AuthenticationTokenTextBlock_Watermark", resourceCulture);
            }
        }
        
    }
}
