//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optepafi.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PathFindingLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathFindingLocal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optepafi.Assets.Localization.PathFindingLocal", typeof(PathFindingLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MapRepCreat_CancelButton {
            get {
                return ResourceManager.GetString("MapRepCreat_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string MapRepCreat_ReturnDueElevDataAbsenceButton {
            get {
                return ResourceManager.GetString("MapRepCreat_ReturnDueElevDataAbsenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string MapRepCreat_ReturnDueElevDataDistributionAbsenceButton {
            get {
                return ResourceManager.GetString("MapRepCreat_ReturnDueElevDataDistributionAbsenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string MapRepCreat_ReturnDueMapNotSupportedByElevDataTypeButton {
            get {
                return ResourceManager.GetString("MapRepCreat_ReturnDueMapNotSupportedByElevDataTypeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel search.
        /// </summary>
        public static string PathFinding_CancelSearchButton {
            get {
                return ResourceManager.GetString("PathFinding_CancelSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up.
        /// </summary>
        public static string PathFinding_CleanUpButton {
            get {
                return ResourceManager.GetString("PathFinding_CleanUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string PathFinding_ExitButton {
            get {
                return ResourceManager.GetString("PathFinding_ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find path.
        /// </summary>
        public static string PathFinding_FindPathButton {
            get {
                return ResourceManager.GetString("PathFinding_FindPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path finding.
        /// </summary>
        public static string PathFinding_PathFindingHeaderTextBlock {
            get {
                return ResourceManager.GetString("PathFinding_PathFindingHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove last track point.
        /// </summary>
        public static string PathFinding_RemoveLastTrackPoint {
            get {
                return ResourceManager.GetString("PathFinding_RemoveLastTrackPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select searching algorithm.
        /// </summary>
        public static string Settings_AlgorithmSelectingTextBlock {
            get {
                return ResourceManager.GetString("Settings_AlgorithmSelectingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select map representation type.
        /// </summary>
        public static string Settings_MapRepreSelectingTextBlock {
            get {
                return ResourceManager.GetString("Settings_MapRepreSelectingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose map file.
        /// </summary>
        public static string Settings_MapSelectingButton {
            get {
                return ResourceManager.GetString("Settings_MapSelectingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path finding settings.
        /// </summary>
        public static string Settings_PathFindingSettingsHeaderTextBlock {
            get {
                return ResourceManager.GetString("Settings_PathFindingSettingsHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Settings_ProceedingToMapRepreCreation {
            get {
                return ResourceManager.GetString("Settings_ProceedingToMapRepreCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecet template.
        /// </summary>
        public static string Settings_TemplateSelectingTextBlock {
            get {
                return ResourceManager.GetString("Settings_TemplateSelectingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user model file.
        /// </summary>
        public static string Settings_UserModelSelectingButton {
            get {
                return ResourceManager.GetString("Settings_UserModelSelectingButton", resourceCulture);
            }
        }
    }
}
