//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optepafi.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PathFindingLocal_sk_SK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathFindingLocal_sk_SK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optepafi.Assets.Localization.PathFindingLocal.sk-SK", typeof(PathFindingLocal_sk_SK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť.
        /// </summary>
        public static string MapRepCreat_CancelButton {
            get {
                return ResourceManager.GetString("MapRepCreat_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vráť sa.
        /// </summary>
        public static string MapRepCreat_ReturnDueElevDataAbsenceButton {
            get {
                return ResourceManager.GetString("MapRepCreat_ReturnDueElevDataAbsenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vráť sa.
        /// </summary>
        public static string MapRepCreat_ReturnDueElevDataDistributionAbsenceButton {
            get {
                return ResourceManager.GetString("MapRepCreat_ReturnDueElevDataDistributionAbsenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vráť sa.
        /// </summary>
        public static string MapRepCreat_ReturnDueMapNotSupportedByElevDataTypeButton {
            get {
                return ResourceManager.GetString("MapRepCreat_ReturnDueMapNotSupportedByElevDataTypeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerušiť vyhľadávanie.
        /// </summary>
        public static string PathFinding_CancelSearchButton {
            get {
                return ResourceManager.GetString("PathFinding_CancelSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upratať.
        /// </summary>
        public static string PathFinding_CleanUpButton {
            get {
                return ResourceManager.GetString("PathFinding_CleanUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odisť.
        /// </summary>
        public static string PathFinding_ExitButton {
            get {
                return ResourceManager.GetString("PathFinding_ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nájsť cestu.
        /// </summary>
        public static string PathFinding_FindPathButton {
            get {
                return ResourceManager.GetString("PathFinding_FindPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hľadanie ciest.
        /// </summary>
        public static string PathFinding_PathFindingHeaderTextBlock {
            get {
                return ResourceManager.GetString("PathFinding_PathFindingHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstráň posledný bod trate.
        /// </summary>
        public static string PathFinding_RemoveLastTrackPoint {
            get {
                return ResourceManager.GetString("PathFinding_RemoveLastTrackPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber vyhľadávací algoritmus.
        /// </summary>
        public static string Settings_AlgorithmSelectingTextBlock {
            get {
                return ResourceManager.GetString("Settings_AlgorithmSelectingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber súbor s mapou.
        /// </summary>
        public static string Settings_MapSelectingButton {
            get {
                return ResourceManager.GetString("Settings_MapSelectingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia vyhľadávania ciest.
        /// </summary>
        public static string Settings_PathFindingSettingsHeaderTextBlock {
            get {
                return ResourceManager.GetString("Settings_PathFindingSettingsHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovať.
        /// </summary>
        public static string Settings_ProceedingToMapRepreCreation {
            get {
                return ResourceManager.GetString("Settings_ProceedingToMapRepreCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber template.
        /// </summary>
        public static string Settings_TemplateSelectingTextBlock {
            get {
                return ResourceManager.GetString("Settings_TemplateSelectingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber súbor s užívateľským modelom.
        /// </summary>
        public static string Settings_UserModelSelectingButton {
            get {
                return ResourceManager.GetString("Settings_UserModelSelectingButton", resourceCulture);
            }
        }
    }
}
