using Optepafi.Models.SearchingAlgorithmMan.Paths;

namespace Optepafi.Models.ReportMan.Reports;

/// <summary>
/// Represents report of path generated by some algorithm. Path reports are meant to bear and display information and graphics about resulting found paths by algorithm for users.
/// Each implementation of this interface represents some particular type of report for which there should be defined some view model and template for displaying.
/// Reports are aggregated in <see cref="ReportManager"/> / <see cref="ReportSubManager{TVertexAttributes,TEdgeAttributes}"/> by use of appropriate aggregator. They are then returned, converted into view models and presented to user.
/// Report should include graphic source for displaying found path to user.
///
/// This interface provides modification of visitor pattern, so-called "generic visitor pattern".
/// The main goal is not ensuring that caller implements specific method for every <c>IPathReport</c> implementation, but for ability to retrieve objects real type in form of type parameter.
/// </summary>
public interface IPathReport
{
    /// <summary>
    /// One of methods used in generic visitor pattern of <c>IPathReport</c> interface.
    /// For more information on this pattern see <see cref="IPathReportGenericVisitor{TOut,TOtherParams}"/>
    /// </summary>
    /// <param name="genericVisitor">Visiting visitor ;).</param>
    /// <param name="otherParams">Other parameters carried through visitor pattern.</param>
    /// <typeparam name="TOut">Specifies type of return value carried through visitor pattern.</typeparam>
    /// <typeparam name="TOtherParams">Specifies types of the rest of parameters carried through visitor pattern.</typeparam>
    /// <returns>Value of type <c>TOut</c>.</returns>
    TOut AcceptGeneric<TOut, TOtherParams>(IPathReportGenericVisitor<TOut, TOtherParams> genericVisitor, TOtherParams otherParams);
    
    /// <summary>
    /// One of methods used in generic visitor pattern of <c>IPathReport</c> interface.
    /// For more information about this method see <see cref="AcceptGeneric{TOut,TOtherParams}"/>.
    /// </summary>
    TOut AcceptGeneric<TOut>(IPathReportGenericVisitor<TOut> genericVisitor);
}